server:
  port: 1001  # 指定该gateway实例的端口

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
      name: gateway-server
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
