server:
  port: 8011
spring:
  application:
    name: consumer-feign
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true
feign:
  hystrix:
    enabled: true